FROM registry.access.redhat.com/ubi8/ubi:8.7

RUN dnf install -y \
           buildah \
           git-lfs \
           java-11-openjdk-devel \
           maven && \
    dnf clean all

RUN useradd imaginator && \
    echo imaginator:10000:5000 > /etc/subuid && \
    echo imaginator:10000:5000 > /etc/subgid


USER imaginator
WORKDIR /home/imaginator

RUN git clone https://github.com/heathmorgan/public-sandbox
